### ISSUE TITLE
This existed since mid 2021..

### ISSUE THREAD

**Issue by Zane2b2t** [CDAGaming/CrystalOptimizer#2]
HvH cheats had this since mid 2021
Marlow skidded it and now hes getting all credits for it.

**Comment by CDAGaming** [comment]
I can agree on the fact that this was a very simplistic mod to manufacture, Marlow was simply the one to popularize it through their videos.

As for this repo, I built it to take advantage of the increased traffic and for research purposes on the impact it could have if it was more widely available (A lot of ac devs found it impossible to prevent cw due to its nature, which was the direct inspiration to make it more of a threat via this optimizer -- If they wont solve the problem at hand by their own volition, Ill prove it can easily grow to where everyone uses it, which is what the repo was designed to do, and is doing as planned)
